# Generated by Django 4.2.1 on 2023-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_cliente', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefono', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('patente', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('comentarios', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField()),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('numero_habitacion', models.PositiveSmallIntegerField()),
                ('comentarios', models.TextField(null=True)),
            ],
        ),
    ]
