# Generated by Django 4.2.1 on 2023-06-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='garaje',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
